name: Index Docebo Content

on:
  # Triggers the workflow every day at midnight.
  schedule:
    - cron: "0 0 * * *"
  # Enables the workflow to be triggered from Github.
  workflow_dispatch:

env:
  DOCEBO_COURSES_ARTIFACT: docebo-courses
  DOCEBO_COURSES_FILENAME: docebo-courses.json

jobs:
  download_course_data:
    runs-on: ubuntu-latest
    steps:
      # @see https://github.com/marketplace/actions/http-request-action
      # @see https://usertesting.docebosaas.com/api-browser/#!/course/Courses/Courses_course_v1_courses
      - name: Download course data from Docebo API.
        id: downloadCourseData
        uses: fjogeleit/http-request-action@master
        with:
          url: https://usertesting.docebosaas.com/course/v1/courses?status[]=published
          method: GET
          
      - name: Create file from API response.
        shell: bash
        run: |
          echo ${{ steps.myRequest.outputs.response }} > $DOCEBO_COURSES_FILENAME
      
      # @see https://github.com/actions/upload-artifact
      # @see https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Upload course data file.
        uses: actions/upload-artifact@v2
        with:
          name: $DOCEBO_COURSES_ARTIFACT
          path: $DOCEBO_COURSES_FILENAME
          retention-days: 1
  
  index_courses_data:
    runs-on: ubuntu-latest
    needs: download_course_data
    steps:
      # @see https://github.com/actions/download-artifact
      - name: Download Docebo course data.
        uses: actions/download-artifact@v2
        with:
          name: $DOCEBO_COURSES_ARTIFACT       
        
      # @see https://github.com/marketplace/actions/checkout
      - name: Checkout this repository.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # @see https://github.com/marketplace/actions/algolia-uploader
      - name: Upload content to Algolia.
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.APP_ID }}
          admin_key: ${{ secrets.ADMIN_KEY }}
          index_name: ${{ secrets.INDEX_NAME }}
          index_file_path: test-data/docebo-records.json
