name: Index Docebo Content

# Controls when the workflow will run
on:
  # Triggers the workflow every day at midnight.
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  index_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upload content to Algolia.
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.APP_ID }}
          admin_key: ${{ secrets.ADMIN_KEY }}
          index_name: ${{ secrets.INDEX_NAME }}
          index_file_path: test-data/docebo-records.json
