name: Index Docebo Content

on:
  # Triggers the workflow every day at midnight.
  schedule:
    - cron: "0 0 * * *"
  # Enables the workflow to be triggered from Github.
  workflow_dispatch:

jobs:
  download_and_index_courses:
    runs-on: ubuntu-latest
    steps:
      # @see https://github.com/marketplace/actions/http-request-action
      # @see https://usertesting.docebosaas.com/api-browser/#!/course/Courses/Courses_course_v1_courses
      - name: Download course data.
        id: downloadCourseData
        uses: fjogeleit/http-request-action@master
        with:
          url: https://usertesting.docebosaas.com/course/v1/courses?status[]=published
          method: GET
          
      - name: Create tmp directory.
        run: mkdir ${{ env.home }}/tmp
        if: always()
        
      # @see https://github.com/marketplace/actions/write-file
      - name: Create file from API data.
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{ env.home }}/tmp/courses.json
          contents: |
            echo ${{ steps.downloadCourseData.outputs.response }}
          write-mode: overwrite
        if: always()
          
      - name: Show file and contents.
        run: |
          ls -hal ${{ env.home }}/tmp/
          head -n10 ${{ env.home }}/tmp/courses.json
        shell: bash
        if: always()
        
      # @see https://github.com/marketplace/actions/checkout
      - name: Checkout this repository.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # @see https://github.com/marketplace/actions/algolia-uploader
      - name: Upload content to Algolia.
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.APP_ID }}
          admin_key: ${{ secrets.ADMIN_KEY }}
          index_name: ${{ secrets.INDEX_NAME }}
          index_file_path: test-data/docebo-records.json
