name: Index Docebo Content

on:
  # Triggers the workflow every day at midnight.
  schedule:
    - cron: "0 0 * * *"
  # Enables the workflow to be triggered from Github.
  workflow_dispatch:

jobs:
  download_and_index_courses:
    runs-on: ubuntu-latest
    steps:
      # @see https://github.com/marketplace/actions/http-request-action
      - name: Download course data
        id: downloadCourseData
        uses: fjogeleit/http-request-action@master
        with:
          url: https://usertesting.docebosaas.com/course/v1/courses?status[]=published
          method: GET
          
      - name: Show Response
        run: echo ${{ steps.downloadCourseData.outputs.response }}
        
      # @see https://github.com/marketplace/actions/checkout
      - name: Checkout this repository.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # @see https://github.com/marketplace/actions/algolia-uploader
      - name: Upload content to Algolia.
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.APP_ID }}
          admin_key: ${{ secrets.ADMIN_KEY }}
          index_name: ${{ secrets.INDEX_NAME }}
          index_file_path: test-data/docebo-records.json
