name: Index Docebo Content

on:
  # Triggers the workflow every day at midnight.
  schedule:
    - cron: "0 0 * * *"
  # Enables the workflow to be triggered from Github.
  workflow_dispatch:

env:
  DOCEBO_API_URL: https://usertesting.docebosaas.com/course
  DOCEBO_API_ROUTE: v1/courses
  DOCEBO_API_QUERY: status[]=published
  DOCEBO_RESULTS_FILE: courses.json

jobs:
  download_and_index_courses:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -o "$DOCEBO_RESULTS_FILE" "$DOCEBO_API_URL/$DOCEBO_API_ROUTE?$DOCEBO_API_QUERY"
      - name: TEST display courses.json content.
        shell: bash
        run: |
          value=$(cat "$DOCEBO_RESULTS_FILE")
          echo "$value"
        if: always()
      - name: Checkout this repository.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upload content to Algolia.
        uses: wangchucheng/algolia-uploader@master
        with:
          app_id: ${{ secrets.APP_ID }}
          admin_key: ${{ secrets.ADMIN_KEY }}
          index_name: ${{ secrets.INDEX_NAME }}
          index_file_path: test-data/docebo-records.json
